src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenue;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class, inversedBy="messages")
     */
    private $subject;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenue(): ?string
    {
        return $this->contenue;
    }

    public function setContenue(?string $contenue): self
    {
        $this->contenue = $contenue;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
}

src/Controller/SubjectDefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//request 
use Symfony\Component\HttpFoundation\Request;
//Entity
use App\Entity\Subject;
use App\Entity\Message;
//Repository
use App\Repository\SubjectRepository;
use App\Repository\MessageRepository;

class SubjectDefaultController extends AbstractController
{
    /**
     * @Route("/subject/default{subjectId}", name="app_subject_default")
     */
    public function index(SubjectRepository $subject, MessageRepository $message, $subjectId): Response
    {
        //Get the subject from the database
        $subject = $subject->find($subjectId);
        //Get all messages from the database
        $messages = $message->findBy(['subject' => $subject], ['date_created' => 'ASC']);
        
        return $this->render('subject_default/index.html.twig', [
            'controller_name' => 'SubjectDefaultController',
            'subject' => $subject,
            'messages' => $messages,
        ]);
    }
}

templates/subject_default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SubjectDefaultController!
{% endblock %}

{% block body %}
	<div class="container">
		<a href="{{ path('app_message', {'subjectId': subject.id}) }}" class="btn btn-success">Ajouter un message</a>
		<div class="row">
			<div class="col-md-12 p-3 ">
				<h1>Sujet :
					{{subject.name}}
					- Créer le
					{{subject.dateCreated |date('d-m-Y') }}</h1>
			</div>
			{% for message in messages %}
				<div class="col-md-12 px-5">
					<h2>{{message.contenue}}</h2>
					<p>{{message.dateCreated |date('d-m-Y') }}</p>
				</div>
			{% endfor %}
		{% endblock %}